spring:
  profiles:
    active: dev
resource:
  url:
    base: https://hacker-news.firebaseio.com/
    top: https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty
    item: https://hacker-news.firebaseio.com/v0/item/
    maxId: https://hacker-news.firebaseio.com/v0/maxitem.json?print=pretty
    user: https://hacker-news.firebaseio.com/v0/user/